
import './vendors/methods'
import './customers/methods'
import './users/server'
import './employees/method'
import './category/method'
import './units/methods'
import './sale/method'
import './Item/method'
import './purchase/method'
import './reciept/method'